# Generated by Django 6.1.1 on 2026-09-29 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profils',
            name='addres',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profils',
            name='phon_num',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
