# Generated by Django 6.1.1 on 2026-09-29 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profils_addres_profils_phon_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profils',
            name='addres',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profils',
            name='phon_num',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
