# Generated by Django 6.1.1 on 2026-10-01 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('books', 'Books'), ('games', 'Games'), ('cars', 'Cars')], max_length=50),
        ),
    ]
